routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\GeneralController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CalendaryController;
use App\Http\Controllers\PinController;
use App\Http\Controllers\SubscriberController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
//GESTIONE UTENTI
Route::get('/users',[UserController::class,'index'])->name('users')->middleware(['auth', 'verified']);
Route::post('/editUser{id}',[UserController::class,'edit'])->name('users.edit')->middleware(['auth', 'verified']);
Route::post('/updateUser/{user}',[UserController::class,'update'])->name('users.update')->middleware(['auth', 'verified']);
Route::get('/userCreate',[UserController::class,'create'])->name('users.create')->middleware(['auth', 'verified']);
Route::post('/userStore',[UserController::class,'store'])->name('registra')->middleware(['auth', 'verified']);
Route::post('/verificapin',[PinController::class,'verificapin'])->name('verificapin');

//GESTIONE RUOLI
Route::get('/role',[RoleController::class,'index'])->name('role')->middleware(['auth', 'verified']);
Route::get('/roleCreate',[RoleController::class,'create'])->name('role.create')->middleware(['auth', 'verified']);
Route::post('/roleStore',[RoleController::class,'store'])->name('role.store')->middleware(['auth', 'verified']);
Route::post('/editRole{role}',[RoleController::class,'edit'])->name('role.edit')->middleware(['auth', 'verified']);
Route::post('/deleteRole{id}',[RoleController::class,'destroy'])->name('role.delete')->middleware(['auth', 'verified']);
Route::post('/updateRole/{role}',[RoleController::class,'update'])->name('role.update')->middleware(['auth', 'verified']);

//GESTIONE GALLERY
Route::get('/gallery',[GalleryController::class,'index'])->name('gallery')->middleware(['auth', 'verified']);
Route::get('/galleryCreate',[GalleryController::class,'create'])->name('gallery.create')->middleware(['auth', 'verified']);
Route::post('/galleryStore',[GalleryController::class,'store'])->name('gallery.store')->middleware(['auth', 'verified']);
Route::post('/editGallery{gallery}',[GalleryController::class,'edit'])->name('gallery.edit')->middleware(['auth', 'verified']);
Route::post('/deleteGallery{gallery}',[GalleryController::class,'destroy'])->name('gallery.delete')->middleware(['auth', 'verified']);

//GESTIONE CATEGORIE
Route::get('/category',[CategoryController::class,'index'])->name('category')->middleware(['auth', 'verified']);
Route::get('/categoryCreate',[CategoryController::class,'create'])->name('category.create')->middleware(['auth', 'verified']);
Route::post('/categoryStore',[CategoryController::class,'store'])->name('category.store')->middleware(['auth', 'verified']);
Route::post('/editcategory{category}',[CategoryController::class,'edit'])->name('category.edit')->middleware(['auth', 'verified']);
Route::post('/deletecategory{category}',[CategoryController::class,'destroy'])->name('category.delete')->middleware(['auth', 'verified']);

//GESTIONE CALENDARIO
Route::get('/calendary',[CalendaryController::class,'index'])->name('calendary')->middleware(['auth', 'verified']);
Route::get('/calendaryCreate',[CalendaryController::class,'create'])->name('calendary.create')->middleware(['auth', 'verified']);
Route::post('/calendaryStore',[CalendaryController::class,'store'])->name('calendary.store')->middleware(['auth', 'verified']);
Route::any('/editcalendary{calendary}',[CalendaryController::class,'edit'])->name('calendary.edit')->middleware(['auth', 'verified']);
Route::any('/deletecalendary{calendary}',[CalendaryController::class,'destroy'])->name('calendary.delete')->middleware(['auth', 'verified']);
Route::any('/updatecalendary{calendary}',[CalendaryController::class,'update'])->name('calendary.update')->middleware(['auth', 'verified']);

//GESTIONE MAIL
Route::post('/mail',[SubscriberController::class,'inviomail'])->name('email');








require __DIR__.'/auth.php';

app/Models/gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class gallery extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_category',
        'path',
    ];

    public function category(){
        return $this->belongsTo(category::class,'id_category','id');
     }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Models\gallery;
use App\Models\category;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Intervention\Image\Facades\Image as ResizeImage;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(gallery $gallery)
    {
        $galleries=gallery::with('category')->get()->groupBy('category.name');
        $category=category::all();
        
        return view('gallery.gallery',compact('galleries','category'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(category $categorie)
    {
        $categorie=category::all();
        return view('gallery.create',compact('categorie'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request, gallery $gallery,category $categoria)
    {

        
        
        
        $save_pathThumb="images/categoria/thumbnails/".$request->categorie;
        $save_pathOriginal="images/categoria/".$request->categorie;
        $image = $request->file('immagine');
        $input['imagename'] = time().'.'.$image->extension();
        if (!file_exists($save_pathThumb)) {
            mkdir($save_pathThumb, 666, true);
        }
        $destinationPath = storage_path($save_pathThumb.'/thumbnail');
        //dd($destinationPath.'/'.$input['imagename']);
        $img = Image::make($image->path());
        $img->resize(800, 600, function ($constraint) {
            $constraint->aspectRatio();
        })->save("images/categoria/thumbnails/".$request->categorie.'/'.$input['imagename']);
   
        $destinationPath = storage_path($save_pathOriginal);
        $image->move($destinationPath, $input['imagename']);
        
        $gallery->id_category=$request->categorie;
        $gallery->path="storage/categoria/".$gallery->id_category."/".$input['imagename'];
        $gallery->copertina=$request->copertina;
        //dd($gallery);
        $gallery->save();
        $gallery->id;
        
        $galleries=gallery::all();
        $category=category::all();
        //return view('gallery.gallery',compact('galleries','category'));
        return redirect()->back()->with('message','Foto inserita correttamente');
    }

    /**
     * Display the specified resource.
     */
    public function show(gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(gallery $gallery)
    {
        //dd($gallery->id_category);
        $oldcopertina=gallery::where('id_category',$gallery->id_category)->where('copertina',1)->update(['copertina'=>2]);
        $newcopertina=gallery::where('id',$gallery->id)->update(['copertina'=>1]);

        return redirect()->back()->with('message','copertina galleria '.$gallery->category->name.' aggiornata!');
        
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, gallery $gallery)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(gallery $gallery)
    {
        
        $delete=gallery::where('id',$gallery->id)->delete();

        return redirect()->back()->with('message','Foto cancellata correttamente');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/gallery/create.blade.php
@include('layouts.navigation')
<x-guest-layout>
    <div class="container w-50">
        <div class="row justify-content-center">
            <div class="col-12">
                <form method="POST" action="{{ route('gallery.store') }}" enctype="multipart/form-data">
                    @csrf

        <!-- Name -->

                    <x-input-label for="name" :value="__('Nome categoria')" />
                    <select name="categorie" id="categorie" required autofocus>
                            <option value="" disabled selected>--</option>
                        @foreach ($categorie as $categoria)
                            <option value="{{$categoria->id}}">{{$categoria->name}}</option>
                        @endforeach
                    </select>
                    <x-input-label for="nuovonome" id="labelnome" :value="__('Nome categoria')" hidden/>
                    <x-text-input  class="block mt-1 w-full" id="nuovonome" type="text" name="nuovonome" :value="old('nuovonome')" autofocus autocomplete="nuovonome" hidden/>
                    <x-text-input  class="block mt-1 w-full" type="file" name="immagine" :value="old('file')" required autofocus autocomplete="file"/>
                    <x-input-error :messages="$errors->get('name')" class="mt-2" />
                    <x-input-label for="copertina" id="labelnome" :value="__('vuoi impostarla come immagine di copertina?')"/>
                    <select name="copertina" id="">
                        <option value="0" selected>--</option>
                        <option value="1">SI</option>
                        <option value="2">NO</option>
                    </select>
                        <div class="flex items-center justify-end mt-4">
                            <x-primary-button class="ml-4">
                                {{ __('salva') }}
                            </x-primary-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Email Address -->
        

    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script>
        $('#categorie').change(function (e) { 
            e.preventDefault();
            if ($(this).val()=='altro') {
                $('#nuovonome').attr('hidden', false);
                $('#labelnome').attr('hidden', false);
            }else{
                $('#nuovonome').attr('hidden', true);
                $('#labelnome').attr('hidden', true);

            
            }
            
        });
    </script>
</x-guest-layout>

resources/views/gallery/edit.blade.php
<x-guest-layout>
    @foreach ($ruolo as $role)
        
    
    <form action="{{ route('role.update',compact('role')) }}"method="post" >
        @csrf
        
        <!-- Name -->
        <div>
            <x-input-label for="name" :value="__('Name')" />
            <x-text-input id="name" class="block mt-1 w-full" type="text" name="ruolo" :value="old('ruolo')" required autofocus autocomplete="name" />
            <x-input-error :messages="$errors->get('name')" class="mt-2" />
        </div>
        <div class="flex items-center justify-end mt-4">
            <x-primary-button class="ml-4">
                {{ __('salva') }}
            </x-primary-button>
        </div>
    </form>
    @endforeach
</x-guest-layout>

resources/views/gallery/gallery.blade.php
<x-app-layout>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
            @if (Session::has('message'))
                <div class="alert alert-success">
                    {{session('message')}}
                </div>
            @endif
            </div>
        </div>
    </div>
    {{-- GESTIONE CATEGORIE --}}
    <div class="container-xxl" style="margin-top: 100px">
        <div class="row justify-content-center">
            <div class="col-6 text-center">
                <button id="category" class="fas fa-plus-circle btn btn-success"><p style="color:white;"> Gestisci Categorie </p></button>
            </div>
            <div class="col-6 text-center">
                <a href="{{route('gallery.create')}}"><p class="fas fa-plus-circle btn btn-success" style="color:white;font-size:1rem;margin-left:-7rem;"> Aggiungi Immagine</p></a>
            </div>
        </div>
    </div>
    <div class="container mt-5" >
        <div class="row justify-content-center">
            <div class="col-12 text-center"id="tabcat" style="display:none">
                <table class="table table-dark rounded" >
                    <thead>
                        <tr>
                            <th>Nome categoria</th>
                            <th>Azioni</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($category as $cat)
                        <tr>
                            <td>{{$cat->name}}</td>
                            <td>
                                <button class="btn btn-dark">Modifica</button>
                                <button class="btn btn-dark">Elimina</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <button class="btn btn-custom" id="aggiungicat">Aggiungi Categoria</button>
                <div class="container w-50" id="newcatform" style="display:none">
                    <div class="row justify-content-center">
                        <div class="col-12">
                            <form method="POST" action="{{ route('category.store') }}" enctype="multipart/form-data">
                                @csrf
            
                    <!-- Name -->
            
                                <x-input-label for="name" :value="__('Nome categoria')" />
                                <x-text-input  class="block mt-1 w-full" id="name" type="text" name="name" :value="old('name')" autofocus autocomplete="name" placeholder="inserisci nome categoria"/>
                                <div class="flex items-center justify-end mt-4">
                                        <x-primary-button class="ml-4">
                                            {{ __('salva') }}
                                        </x-primary-button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    {{-- FINE GESTIONE CATEGORIE --}}

    {{-- GESTIONE GALLERY E FOTO --}}
    <div class="container-fluid">
        <div class="row justify-content-center">
                @foreach ($galleries as $gallery => $values)
                <div class="col-12 mt-5 text-center">
                    <h2 class="text-start m-3 bg-danger p-2 rounded text-center"><span class="colorefirst">Galleria: </span><span class="text-white">{{$gallery}}</span></h2>
                    <div class="container">
                        <div class="row justify-content-center">
                            @foreach ($values as $value)
                            <div class="galleryItem card col-12 col-sm-12 col-md-12 col-lg-3">
                                @if ($value->copertina==1)
                                <div class="ribbon">
                                    <span>COPERTINA</span>
                                </div>
                                @endif
                                <img src="{{asset(''.$value->path.'') }}" class="img-fluid" style="width:100%;height:358px">
                                <figcaption class="box__caption container-fluid">
                                        <div class="row justify-content-center">
                                            <div class="col-5 text-center">
                                                <form action="{{route('gallery.delete',$value->id)}}" method="POST">
                                                    @csrf
                                                    <button class="btn btn-danger" style="font-size: 0.7rem;">elimina</button>
                                                </form>
                                            </div>
                                            <div class="col-5 text-center">
                                                <form action="{{route('gallery.edit',$value->id)}}" method="POST">
                                                    @csrf
                                                    <button class="btn btn-danger" style="font-size: 0.7rem;">copertina</button>
                                                </form>
                                            </div>
                                        </div>
                            </figcaption>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        {{-- FINE GALLERY E FOTO --}}

        <script>
            $('#category').click(function (e) { 
                e.preventDefault();
                $('#tabcat').toggle(400);
            });

            $('#aggiungicat').click(function (e) { 
                e.preventDefault();
                $('#newcatform').toggle(400);
            });
        </script>
    
</x-app-layout>